FROM ubuntu:22.04

RUN apt update && \
    apt install -y openssh-server tmate sudo curl && \
    useradd -m vpsuser && \
    echo 'vpsuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]